server:
  port: 9999

logging:
  config: classpath:logback.xml

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/melon?useSSL=false
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      username: root
      password: 1234
      maximum-pool-size: 30

mybatis:
  configuration:
    map-underscore-to-camel-case: true

task:
  thread:
    num: 20
